# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: ilammy/setup-nasm@v1

    - name: Setup Environment
      run: |
        sudo apt-get install gcc
       
        export CC=/usr/local/bin/gcc
        export LD=/usr/local/bin/gcc

        export PREFIX="/usr/local/i386elfgcc"
        export TARGET=i386-elf
        export PATH="$PREFIX/bin:$PATH"

        mkdir /tmp/src
        cd /tmp/src
        curl -O http://ftp.gnu.org/gnu/binutils/binutils-2.35.tar.gz
        tar xf binutils-2.35.tar.gz
        mkdir binutils-build
        cd binutils-build
        ../binutils-2.35/configure --target=$TARGET --enable-interwork --enable-multilib --disable-nls --disable-werror --prefix=$PREFIX 2>&1 | tee configure.log
        sudo make all install 2>&1 | tee make.log
        
        cd /tmp/src
        curl -O https://ftp.gnu.org/gnu/gcc/gcc-10.2.0/gcc-10.2.0.tar.gz
        tar xf gcc-10.2.0.tar.gz
        mkdir gcc-build
        cd gcc-build
        ../gcc-10.2.0/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --disable-libssp --enable-languages=c --without-headers
        make all-gcc 
        make all-target-libgcc 
        sudo make install-gcc 
        sudo make install-target-libgcc 

    - name: Build OS
      run: |
        cd os
        make
        make clean
